export const RPC_URL = process.env.REACT_APP_SEPOLIA_RPC_URL;
export const TAB_CONTRACT_ADDRESS = process.env.REACT_APP_TAB_CONTRACT_ADDRESS;
export const TASK_CONTRACT_ADDRESS =
  process.env.REACT_APP_TASK_CONTRACT_ADDRESS;
